# Forex Data Analysis

This notebook reads EUR/USD exchange rate data and displays it in a table format.

In [563]:
import pandas as pd
import numpy as np
from IPython.display import display, HTML

# Read the EUR/USD data from CSV file
df = pd.read_csv('./eurusd.csv', keep_default_na=False)

# Returns percentage of value over total
def percentage(value, total):
    return f"{value / total * 100:.1f}%"

# Returns int or 0 if error
def safe_int(value):
    try:
        return int(value)
    except:
        return 0.0

display(
    HTML("<h2>Profitable Trades</h2><p>What are simple trading ideas that are profitable?</p>")
)
df_profitable = pd.DataFrame({
    'Data': [
        'Total',
        'With Extra',
        'Buy Only',
        'Sell Only',
        'With EMA',
        'Against EMA',
        'BOS Trades',
        'CH Trades',
        'With EMA & BOS',
        'With EMA & CH',
    ],
    '1:1 RRR': [
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'])].shape[0], df.shape[0]),
        percentage(df[((df['SL'] != df['Pullback']) | ((df['SL'] == df['Pullback']) & (df['Extra'] != ''))) & (df['TP'] >= df['SL'] + safe_int(df['Extra']))].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL']) & (df['Direction'] == 'Buy')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL']) & (df['Direction'] == 'Sell')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL']) & (df['EMA'] == df['Direction'])].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL']) & (df['EMA'] != df['Direction'])].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL']) & (df['BOS/CH'] == 'BOS')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL']) & (df['BOS/CH'] == 'CH')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL']) & (df['EMA'] == df['Direction']) & (df['BOS/CH'] == 'BOS')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL']) & (df['EMA'] == df['Direction']) & (df['BOS/CH'] == 'CH')].shape[0], df.shape[0]),
    ],
    '1:2 RRR': [
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 2)].shape[0], df.shape[0]),
        percentage(df[((df['SL'] != df['Pullback']) | ((df['SL'] == df['Pullback']) & (df['Extra'] != ''))) & (df['TP'] >= (df['SL'] + safe_int(df['Extra'])) * 2)].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 2) & (df['Direction'] == 'Buy')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 2) & (df['Direction'] == 'Sell')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 2) & (df['EMA'] == df['Direction'])].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 2) & (df['EMA'] != df['Direction'])].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 2) & (df['BOS/CH'] == 'BOS')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 2) & (df['BOS/CH'] == 'CH')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 2) & (df['EMA'] == df['Direction']) & (df['BOS/CH'] == 'BOS')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 2) & (df['EMA'] == df['Direction']) & (df['BOS/CH'] == 'CH')].shape[0], df.shape[0]),
    ],
    '1:3 RRR': [
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 3)].shape[0], df.shape[0]),
        percentage(df[((df['SL'] != df['Pullback']) | ((df['SL'] == df['Pullback']) & (df['Extra'] != ''))) & (df['TP'] >= (df['SL'] + safe_int(df['Extra'])) * 3)].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 3) & (df['Direction'] == 'Buy')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 3) & (df['Direction'] == 'Sell')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 3) & (df['EMA'] == df['Direction'])].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 3) & (df['EMA'] != df['Direction'])].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 3) & (df['BOS/CH'] == 'BOS')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 3) & (df['BOS/CH'] == 'CH')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 3) & (df['EMA'] == df['Direction']) & (df['BOS/CH'] == 'BOS')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 3) & (df['EMA'] == df['Direction']) & (df['BOS/CH'] == 'CH')].shape[0], df.shape[0]),
    ]
})
df_profitable['Value_num'] = df_profitable['1:1 RRR'].str.rstrip('%').astype(float)
df_bos_sorted = df_profitable.sort_values('Value_num', ascending=False).drop(columns='Value_num').reset_index(drop=True)
df_bos_sorted

             Data 1:1 RRR 1:2 RRR 1:3 RRR
0      With Extra   54.2%   41.7%   37.5%
1           Total   45.8%   33.3%   29.2%
2      BOS Trades   33.3%   20.8%   20.8%
3        With EMA   29.2%   16.7%   12.5%
4        Buy Only   25.0%   16.7%   12.5%
5  With EMA & BOS   25.0%   12.5%   12.5%
6       Sell Only   20.8%   16.7%   16.7%
7     Against EMA   16.7%   16.7%   16.7%
8       CH Trades   12.5%   12.5%    8.3%
9   With EMA & CH    4.2%    4.2%    0.0%

In [564]:
display(
    HTML("<h2>When To Enter</h2><p>Following market structure, price taps order block. This is when the signal is received. Now - when to enter the trade?</p>")
)
profitable_5m_cc = len(df[(df['SL'] != df['Pullback']) & (df['TP'] > safe_int(df['SL 5M CC']))].index)
profitable_5m_stop = len(df[(df['SL'] != df['Pullback']) & (df['TP'] > safe_int(df['SL 5M Stop']))].index)
profitable_5m_breakout = len(df[(df['SL'] != df['Pullback']) & (df['TP'] > safe_int(df['SL Breakout']))].index)
df_bos = pd.DataFrame({
    'Idea': [
        '1M Confirmation Candle',
        '5M Confirmation Candle',
        '5M Stop',
        '5M Breakout',
    ],
    'Count': [
        str(len(df[(df['SL'] != df['Pullback']) & (df['TP'] > df['SL'])].index)) + 'W - ' + str(len(df[(df['SL'] == df['Pullback']) | (df['TP'] <= df['SL'])].index)) + 'L',
        str(profitable_5m_cc) + 'W - ' + str(len(df[df['SL 5M CC'] != '']) - profitable_5m_cc) + 'L',
        str(profitable_5m_stop) + 'W - ' + str(len(df[df['SL 5M Stop'] != '']) - profitable_5m_stop) + 'L',
        str(profitable_5m_breakout) + 'W - ' + str(len(df[df['SL Breakout'] != '']) - profitable_5m_breakout) + 'L',
    ],
    'Percentage': [
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] > df['SL'])].shape[0], len(df['SL'])),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] > safe_int(df['SL 5M CC']))].shape[0], len(df[df['SL 5M CC'] != ''])),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] > safe_int(df['SL 5M Stop']))].shape[0], len(df[df['SL 5M Stop'] != ''])),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] > safe_int(df['SL Breakout']))].shape[0], len(df[df['SL Breakout'] != ''])),
    ],
})
df_bos['Value_num'] = df_bos['Percentage'].str.rstrip('%').astype(float)
df_bos_sorted = df_bos.sort_values('Value_num', ascending=False).drop(columns='Value_num').reset_index(drop=True)
df_bos_sorted

                     Idea      Count Percentage
0             5M Breakout   11W - 5L      68.8%
1                 5M Stop   11W - 6L      64.7%
2  5M Confirmation Candle   11W - 9L      55.0%
3  1M Confirmation Candle  11W - 13L      45.8%

In [565]:
display(
    HTML("<h2>BOS Breakdown</h2><p>If BOS trades have highest chances, what about BOS + something else?</p>")
)
df_bos = pd.DataFrame({
    'Idea': [
        'BOS Trades',
        'BOS + Buy',
        'BOS + Sell',
        'BOS + EMA',
        'BOS + Against EMA',
        'BOS + HTF Buy',
        'BOS + HTF Sell',
        'BOS + News',
        'BOS + Without News',
    ],
    '1:1 RRR': [
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL']) & (df['BOS/CH'] == 'BOS')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL']) & (df['BOS/CH'] == 'BOS') & (df['Direction'] == 'Buy')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL']) & (df['BOS/CH'] == 'BOS') & (df['Direction'] == 'Sell')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL']) & (df['BOS/CH'] == 'BOS') & (df['EMA'] == df['Direction'])].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL']) & (df['BOS/CH'] == 'BOS') & (df['EMA'] != df['Direction'])].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL']) & (df['BOS/CH'] == 'BOS') & (df['30M Leg'].isin(['Above H', 'Above L']))].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL']) & (df['BOS/CH'] == 'BOS') & (df['30M Leg'].isin(['Below H', 'Below L']))].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL']) & (df['BOS/CH'] == 'BOS') & (df['News Event'].isna())].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL']) & (df['BOS/CH'] == 'BOS') & (~df['News Event'].isna())].shape[0], df.shape[0]),
    ],
    '1:2 RRR': [
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 2) & (df['BOS/CH'] == 'BOS')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 2) & (df['BOS/CH'] == 'BOS') & (df['Direction'] == 'Buy')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 2) & (df['BOS/CH'] == 'BOS') & (df['Direction'] == 'Sell')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 2) & (df['BOS/CH'] == 'BOS') & (df['EMA'] == df['Direction'])].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 2) & (df['BOS/CH'] == 'BOS') & (df['EMA'] != df['Direction'])].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 2) & (df['BOS/CH'] == 'BOS') & (df['30M Leg'].isin(['Above H', 'Above L']))].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 2) & (df['BOS/CH'] == 'BOS') & (df['30M Leg'].isin(['Below H', 'Below L']))].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 2) & (df['BOS/CH'] == 'BOS') & (df['News Event'].isna())].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 2) & (df['BOS/CH'] == 'BOS') & (~df['News Event'].isna())].shape[0], df.shape[0]),
    ],
    '1:3 RRR': [
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 3) & (df['BOS/CH'] == 'BOS')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 3) & (df['BOS/CH'] == 'BOS') & (df['Direction'] == 'Buy')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 3) & (df['BOS/CH'] == 'BOS') & (df['Direction'] == 'Sell')].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 3) & (df['BOS/CH'] == 'BOS') & (df['EMA'] == df['Direction'])].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 3) & (df['BOS/CH'] == 'BOS') & (df['EMA'] != df['Direction'])].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 3) & (df['BOS/CH'] == 'BOS') & (df['30M Leg'].isin(['Above H', 'Above L']))].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 3) & (df['BOS/CH'] == 'BOS') & (df['30M Leg'].isin(['Below H', 'Below L']))].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 3) & (df['BOS/CH'] == 'BOS') & (df['News Event'].isna())].shape[0], df.shape[0]),
        percentage(df[(df['SL'] != df['Pullback']) & (df['TP'] >= df['SL'] * 3) & (df['BOS/CH'] == 'BOS') & (~df['News Event'].isna())].shape[0], df.shape[0]),
    ]
})
df_bos['Value_num'] = df_bos['1:1 RRR'].str.rstrip('%').astype(float)
df_bos_sorted = df_bos.sort_values('Value_num', ascending=False).drop(columns='Value_num').reset_index(drop=True)
df_bos_sorted

                 Idea 1:1 RRR 1:2 RRR 1:3 RRR
0          BOS Trades   33.3%   20.8%   20.8%
1  BOS + Without News   33.3%   20.8%   20.8%
2           BOS + EMA   25.0%   12.5%   12.5%
3      BOS + HTF Sell   25.0%   16.7%   16.7%
4           BOS + Buy   16.7%    8.3%    8.3%
5          BOS + Sell   16.7%   12.5%   12.5%
6   BOS + Against EMA    8.3%    8.3%    8.3%
7       BOS + HTF Buy    8.3%    4.2%    4.2%
8          BOS + News    0.0%    0.0%    0.0%

In [566]:
# Define RRR calculation function
def calculate_rrr_stats(data_df, strategy_name):
    """
    Calculate Risk-Reward Ratio statistics for a given dataframe and strategy.
    
    Args:
        data_df: DataFrame containing trading data
        strategy_name: Name of the strategy for labeling
    
    Returns:
        DataFrame with RRR statistics
    """
    total_trades = len(data_df)
    
    rrr_configs = [
        (1, 50.0),   # 1:1 RRR needs 50% win rate to break even
        (2, 33.0),   # 1:2 RRR needs 33% win rate to break even
        (3, 25.0),   # 1:3 RRR needs 25% win rate to break even
    ]
    
    if total_trades == 0:
        summary_data = {
            strategy_name: ['Total trades', 'Wins', 'Losses', 'Win Rate', 'Edge', 'Outcome']
        }
        for ratio, breakeven_rate in rrr_configs:
            summary_data[f'1:{ratio} RRR'] = [0, 0, 0, '0.0%', '0.0%', '0R']
        return pd.DataFrame(summary_data)
    
    
    summary_data = {
        strategy_name: ['Total trades', 'Wins', 'Losses', 'Win Rate', 'Edge', 'Outcome']
    }
    
    for ratio, breakeven_rate in rrr_configs:
        profitable = data_df[data_df['TP'] > ratio * data_df['SL']]
        wins = len(profitable)
        losses = total_trades - wins
        win_rate = (wins / total_trades) * 100
        edge = win_rate - breakeven_rate
        outcome = (wins * ratio) - losses
        
        summary_data[f'1:{ratio} RRR'] = [
            total_trades,
            wins,
            losses,
            f"{win_rate:.1f}%",
            f"{edge:.1f}%",
            f"{outcome}R"
        ]
    
    return pd.DataFrame(summary_data)

# Define strategy configurations
class Strategy:
    def __init__(self, name, filter_func, description=""):
        self.name = name
        self.filter_func = filter_func
        self.description = description
    
    def apply(self, df):
        """Apply the strategy filter to the dataframe."""
        return self.filter_func(df)

In [567]:
# Define all strategies in simple format
strategies = [
    Strategy(
        "Plain Strategy",
        lambda df: df,
        "All trades without any filtering"
    ),
    # Strategy(
    #     "1pip Pullback Strategy",
    #     lambda df: df[df['Pullback'] >= 1],
    #     "Trades with at least 1 pip pullback"
    # ),
]

In [568]:
# Generic strategy creator with custom lambdas
def create_custom_strategies(configs):
    """
    Generate multiple strategies with custom filter functions.
    
    Args:
        configs: List of tuples containing (name, filter_lambda, description)
                 where filter_lambda is a function that takes (df, value) as parameters
    
    Example:
        configs = [
            (1, lambda df, v: df[df['Pullback'] >= v], "at least {value} pip pullback"),
            (2, lambda df, v: df[df['Pullback'] >= v], "at least {value} pip pullback"),
        ]
    """
    custom_strategies = []
    for value, filter_func, description_template in configs:
        custom_strategies.append(
            Strategy(
                description_template,
                lambda df, v=value, f=filter_func: f(df, v),
                description_template.format(value=value) if '{value}' in description_template else description_template
            )
        )
    return custom_strategies

# Build tons of strategies
strategies.extend(create_custom_strategies([
    # Basic EMA and Direction Strategies
    (1, lambda df, v: df[df['EMA'] == df['Direction']], "EMA + Trade Direction"),
    (2, lambda df, v: df[df['EMA'] != df['Direction']], "EMA + Opposite Trade Direction"),
    (3, lambda df, v: df[(df['EMA'] == df['Direction']) & (df['BOS/CH'] == 'BOS')], "EMA + BOS"),
    (4, lambda df, v: df[(df['EMA'] == df['Direction']) & (df['BOS/CH'] == 'CH')], "EMA + CH"),
    (5, lambda df, v: df[(df['EMA'] != df['Direction']) & (df['BOS/CH'] == 'CH')], "Opposite EMA + CH"),
    (6, lambda df, v: df[(df['EMA'] != df['Direction']) & (df['BOS/CH'] == 'BOS')], "Opposite EMA + BOS"),
    (7, lambda df, v: df[df['BOS/CH'] == 'BOS'], "BOS"),
    (8, lambda df, v: df[df['BOS/CH'] == 'CH'], "CH"),

    # Risk Management Strategies (SL-based entry filters)
    (9, lambda df, v: df[df['SL'] >= 1], "SL >= 1 pip"),
    (10, lambda df, v: df[df['SL'] >= 2], "SL >= 2 pips"),
    (11, lambda df, v: df[df['SL'] >= 5], "SL >= 5 pips"),
    (12, lambda df, v: df[df['SL'] < 1], "SL < 1 pip"),
    (13, lambda df, v: df[(df['SL'] >= 1) & (df['SL'] <= 3)], "SL 1-3 pips"),
    (14, lambda df, v: df[(df['SL'] >= 3) & (df['SL'] <= 7)], "SL 3-7 pips"),
    (15, lambda df, v: df[(df['SL'] >= 7) & (df['SL'] <= 15)], "SL 7-15 pips"),
    (16, lambda df, v: df[df['SL'] >= 15], "SL >= 15 pips"),
    (17, lambda df, v: df[df['SL'] <= 0.5], "SL <= 0.5 pips"),
    (18, lambda df, v: df[df['SL'] >= 10], "SL >= 10 pips"),

    # Advanced Risk Management Strategies
    (19, lambda df, v: df[df['SL'] <= 2], "Conservative: SL <= 2 pips"),
    (20, lambda df, v: df[df['SL'] >= 3], "Moderate Risk: SL >= 3 pips"),
    (21, lambda df, v: df[df['SL'] >= 5], "Aggressive: SL >= 5 pips"),
    (22, lambda df, v: df[(df['SL'] >= 1) & (df['SL'] <= 3)], "Low Risk Zone: SL 1-3 pips"),
    (23, lambda df, v: df[(df['SL'] >= 3) & (df['SL'] <= 6)], "Medium Risk Zone: SL 3-6 pips"),

    # BOS/CH + SL Strategies (Risk-adjusted market structure)
    (24, lambda df, v: df[(df['BOS/CH'] == 'BOS') & (df['SL'] <= 2)], "BOS + Conservative SL"),
    (25, lambda df, v: df[(df['BOS/CH'] == 'BOS') & (df['SL'] >= 3)], "BOS + Moderate SL"),
    (26, lambda df, v: df[(df['BOS/CH'] == 'CH') & (df['SL'] <= 2)], "CH + Conservative SL"),
    (27, lambda df, v: df[(df['BOS/CH'] == 'CH') & (df['SL'] >= 3)], "CH + Moderate SL"),

    # Weekday Strategies
    (28, lambda df, v: df[df['Weekday'] == 'Monday'], "Monday Only"),
    (29, lambda df, v: df[df['Weekday'] == 'Tuesday'], "Tuesday Only"),
    (30, lambda df, v: df[df['Weekday'] == 'Wednesday'], "Wednesday Only"),
    (31, lambda df, v: df[df['Weekday'] == 'Thursday'], "Thursday Only"),
    (32, lambda df, v: df[df['Weekday'] == 'Friday'], "Friday Only"),
    
    # 30M Leg Trend Strategies
    (33, lambda df, v: df[df['30M Leg'].isin(['Above H', 'Above L'])], "Bullish 30M Trend"),
    (34, lambda df, v: df[df['30M Leg'].isin(['Below H', 'Below L'])], "Bearish 30M Trend"),
    (35, lambda df, v: df[df['30M Leg'] == 'Above H'], "30M Above High"),
    (36, lambda df, v: df[df['30M Leg'] == 'Above L'], "30M Above Low"),
    (37, lambda df, v: df[df['30M Leg'] == 'Below H'], "30M Below High"),
    (38, lambda df, v: df[df['30M Leg'] == 'Below L'], "30M Below Low"),
    
    # News Event Strategies
    (39, lambda df, v: df[df['News Event'].isna()], "No News Events"),
    (40, lambda df, v: df[~df['News Event'].isna()], "News Event Present"),
    (41, lambda df, v: df[(~df['News Event'].isna()) & (df['Hours Until News'] >= 2)], "News in 2+ Hours"),
    (42, lambda df, v: df[(~df['News Event'].isna()) & (df['Hours Until News'] <= 1)], "News in 1 Hour or Less"),
    
    # Combined Strategies: EMA + New Columns
    (43, lambda df, v: df[(df['EMA'] == df['Direction']) & (df['30M Leg'].isin(['Above H', 'Above L']))], "EMA Match + Bullish 30M"),
    (44, lambda df, v: df[(df['EMA'] == df['Direction']) & (df['30M Leg'].isin(['Below H', 'Below L']))], "EMA Match + Bearish 30M"),
    (45, lambda df, v: df[(df['EMA'] == df['Direction']) & (df['News Event'].isna())], "EMA Match + No News"),
    
    # Combined Strategies: BOS/CH + New Columns
    (46, lambda df, v: df[(df['BOS/CH'] == 'BOS') & (df['30M Leg'].isin(['Above H', 'Above L']))], "BOS + Bullish 30M"),
    (47, lambda df, v: df[(df['BOS/CH'] == 'BOS') & (df['30M Leg'].isin(['Below H', 'Below L']))], "BOS + Bearish 30M"),
    (48, lambda df, v: df[(df['BOS/CH'] == 'CH') & (df['30M Leg'].isin(['Above H', 'Above L']))], "CH + Bullish 30M"),
    (49, lambda df, v: df[(df['BOS/CH'] == 'CH') & (df['30M Leg'].isin(['Below H', 'Below L']))], "CH + Bearish 30M"),
    (50, lambda df, v: df[(df['BOS/CH'] == 'BOS') & (df['News Event'].isna())], "BOS + No News"),
    (51, lambda df, v: df[(df['BOS/CH'] == 'CH') & (~df['News Event'].isna())], "CH + News Present"),
    
    # Combined Strategies: 30M Leg + Direction
    (52, lambda df, v: df[(df['Direction'] == 'Buy') & (df['30M Leg'].isin(['Above H', 'Above L']))], "Buy + Bullish 30M"),
    (53, lambda df, v: df[(df['Direction'] == 'Sell') & (df['30M Leg'].isin(['Below H', 'Below L']))], "Sell + Bearish 30M"),
    (54, lambda df, v: df[(df['Direction'] == 'Buy') & (df['30M Leg'].isin(['Below H', 'Below L']))], "Buy + Bearish 30M (Counter)"),
    (55, lambda df, v: df[(df['Direction'] == 'Sell') & (df['30M Leg'].isin(['Above H', 'Above L']))], "Sell + Bullish 30M (Counter)"),
    
    # Combined Strategies: News + Risk
    (56, lambda df, v: df[(df['News Event'].isna()) & (df['SL'] <= 3)], "No News + Low Risk"),
    (57, lambda df, v: df[(~df['News Event'].isna()) & (df['SL'] >= 5)], "News Event + High Risk"),
    (58, lambda df, v: df[(df['Hours Until News'] >= 2) & (df['EMA'] == df['Direction'])], "Far from News + EMA Match"),
    
    # Advanced Trend Alignment
    (59, lambda df, v: df[(df['30M Leg'] == 'Above H') & (df['Direction'] == 'Buy')], "Strong Bullish Alignment"),
    (60, lambda df, v: df[(df['30M Leg'] == 'Below L') & (df['Direction'] == 'Sell')], "Strong Bearish Alignment"),
    (61, lambda df, v: df[(df['30M Leg'] == 'Above L') & (df['BOS/CH'] == 'CH')], "Weak Bullish + CH"),
    (62, lambda df, v: df[(df['30M Leg'] == 'Below H') & (df['BOS/CH'] == 'CH')], "Weak Bearish + CH"),
]))

# Calculate all strategy results
strategy_results = {}
for strategy in strategies:
    filtered_df = strategy.apply(df)
    summary_df = calculate_rrr_stats(filtered_df, strategy.name)
    strategy_results[strategy.name] = summary_df

# Function to get top strategies for a specific RRR
def get_top_strategies_for_rrr(strategy_results, rrr_column, top_n=5):
    """Get top N strategies for a specific RRR based on outcome."""
    strategy_performance = []
    
    for strategy_name, df in strategy_results.items():
        # Extract metrics
        total_trades = df[rrr_column].iloc[0]
        wins = df[rrr_column].iloc[1]
        losses = df[rrr_column].iloc[2]
        win_rate = df[rrr_column].iloc[3]
        edge = df[rrr_column].iloc[4]
        outcome_str = df[rrr_column].iloc[5]
        outcome = int(outcome_str.replace('R', ''))
        
        strategy_performance.append({
            'Strategy': strategy_name,
            'Trades': total_trades,
            'Wins': wins,
            'Losses': losses,
            'Win Rate': win_rate,
            'Edge': edge,
            'Outcome': outcome_str,
            'outcome_value': outcome  # For sorting
        })
    
    # Sort by outcome and get top N
    top_strategies = sorted(strategy_performance, key=lambda x: x['outcome_value'], reverse=True)[:top_n]
    
    # Remove the sorting key from display
    for strat in top_strategies:
        del strat['outcome_value']
    
    return pd.DataFrame(top_strategies)

# Display top 5 strategies for each RRR in separate tables
display(HTML("<h2>TOP Strategies</h2>"))
rrr_configs = [
    ('1:1 RRR', '1:1'),
    ('1:2 RRR', '1:2'),
    ('1:3 RRR', '1:3'),
]
for rrr_column, rrr_label in rrr_configs:
    top_5_df = get_top_strategies_for_rrr(strategy_results, rrr_column, top_n=5)
    top_5_df = top_5_df.rename(columns={'Strategy': 'Best ' + rrr_label + ' RRR Strategies'})
    top_5_df = top_5_df.style.set_properties(
        subset=['Best ' + rrr_label + ' RRR Strategies'], 
        **{'width': '250px'}
    )
    display(top_5_df)
    print()  # Add spacing between tables

TypeError: '>=' not supported between instances of 'str' and 'int'

In [ ]:
# Display all strategy results
display(HTML(f"<h2>All Strategies ({len(strategy_results)})</h2>"))

for strategy_name, summary_df in strategy_results.items():
    # Style the first column to have a fixed width
    styled_df = summary_df.style.set_properties(
        subset=[strategy_name], 
        **{'width': '250px'}
    )
    display(styled_df)
    print('')  # Add spacing between tables