# Forex Strategy Optimizer

This notebook provides a Meta Trader-style strategy tester that exhaustively tests all possible combinations of filters.

## How it works

1. **Filter Dimensions**: Each column from the CSV (EMA, BOS/CH, SL, News, Hour, etc.) becomes a "dimension"
2. **Combinations**: The optimizer generates all possible combinations of these filters
3. **Backtesting**: Each combination is backtested across all RRR ratios (1:1, 1:2, 1:3)
4. **Results**: Strategies are ranked by edge (profitability above breakeven)

## Parameters

- **max_filters**: Maximum number of filters per strategy (e.g., 3 = up to 3 conditions)
- **min_trades**: Minimum trade count required (e.g., 10 trades minimum)
- **min_edge**: Minimum edge percentage required (e.g., 5.0 = 5% above breakeven)
- **top_n**: Show only top N strategies (or None for all)

In [2]:
# Import required libraries
import sys
import importlib

# Add parent directory to path
sys.path.insert(0, '..')

# Enable automatic reloading
%load_ext autoreload
%autoreload 2

# Import utilities
from utils import load_and_clean_data
from utils.optimizer import (
    optimize_strategies,
    display_optimization_results,
    export_optimization_results
)

# Load the data
print("Loading data...")
df = load_and_clean_data()
print(f"Loaded {len(df)} trades")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Loading data...
Loaded 1102 trades

## Quick Test: Top 50 Strategies (Max 2 Filters)

Start with a quick test to see the best double-setup strategies.

In [6]:
# Quick optimization: max 2 filters, top 50 results
results = optimize_strategies(
    df,
    max_filters=2,         # Test up to 2 filters per strategy
    min_filters=1,         # Include single-filter strategies too
    min_trades=100,        # Require at least 100 trades
    min_edge=0.0,          # Show all strategies (even negative edge)
    rrr_ratios=[1, 2, 3],  # Test all RRR ratios
    top_n=None             # Unlimited list
)

display_optimization_results(results, title="Top 50 Strategies (Max 2 Filters)")

Generating strategy combinations (max 2 filters)...
Total combinations to test: 807

Backtesting 807 strategies...
  Processed 500/807 strategies...

Optimization complete! Found 322 strategies meeting criteria.

## Full Optimization: All 3-Filter Combinations

Run a comprehensive test with up to 3 filters per strategy. This will test thousands of combinations.

In [8]:
# Full optimization: max 3 filters, top 100 results
results = optimize_strategies(
    df,
    max_filters=3,         # Test up to 3 filters per strategy
    min_filters=1,         # Include single-filter strategies
    min_trades=200,        # Require at least 100 trades
    min_edge=5.0,          # Only show strategies with 5%+ edge
    rrr_ratios=[1, 2, 3],  # Test all RRR ratios
    top_n=None             # Unlimited
)

display_optimization_results(results, title="Top 100 Strategies (Max 3 Filters, 5%+ Edge)")

Generating strategy combinations (max 3 filters)...
Total combinations to test: 8617

Backtesting 8617 strategies...
  Processed 500/8617 strategies...
  Processed 1000/8617 strategies...
  Processed 1500/8617 strategies...
  Processed 2000/8617 strategies...
  Processed 2500/8617 strategies...
  Processed 3000/8617 strategies...
  Processed 3500/8617 strategies...
  Processed 4000/8617 strategies...
  Processed 4500/8617 strategies...
  Processed 5000/8617 strategies...
  Processed 5500/8617 strategies...
  Processed 6000/8617 strategies...
  Processed 6500/8617 strategies...
  Processed 7000/8617 strategies...
  Processed 7500/8617 strategies...
  Processed 8000/8617 strategies...
  Processed 8500/8617 strategies...

Optimization complete! Found 8 strategies meeting criteria.

## Aggressive Optimization: 4+ Filters

Test complex strategies with 4+ filters. Warning: This can take longer and may overfit to the data.

In [ ]:
# Aggressive optimization: max 4 filters
results = optimize_strategies(
    df,
    max_filters=4,      # Test up to 4 filters per strategy
    min_filters=3,      # Only show 3+ filter strategies
    min_trades=5,       # Lower minimum (complex filters = fewer trades)
    min_edge=10.0,      # High edge threshold (10%+)
    rrr_ratios=[1, 2, 3],
    top_n=50
)

display_optimization_results(results, title="Top 50 Complex Strategies (3-4 Filters, 10%+ Edge)")

## Custom Optimization

Customize your own optimization parameters below:

In [12]:
# Custom optimization - adjust parameters as needed
custom_results = optimize_strategies(
    df,
    max_filters=3,           # Your choice: 1, 2, 3, 4, etc.
    min_filters=1,           # Your choice: 1, 2, 3, etc.
    min_trades=600,           # Your choice: adjust based on data size
    min_edge=0.0,            # Your choice: 0 for all, 5 for 5%+, etc.
    rrr_ratios=[3],    # Your choice: [1], [2], [3], or [1,2,3]
    top_n=None               # Your choice: None for all, or a number
)

display_optimization_results(custom_results, title="Custom Optimization Results")

Generating strategy combinations (max 3 filters)...
Total combinations to test: 8617

Backtesting 8617 strategies...
  Processed 500/8617 strategies...
  Processed 1000/8617 strategies...
  Processed 1500/8617 strategies...
  Processed 2000/8617 strategies...
  Processed 2500/8617 strategies...
  Processed 3000/8617 strategies...
  Processed 3500/8617 strategies...
  Processed 4000/8617 strategies...
  Processed 4500/8617 strategies...
  Processed 5000/8617 strategies...
  Processed 5500/8617 strategies...
  Processed 6000/8617 strategies...
  Processed 6500/8617 strategies...
  Processed 7000/8617 strategies...
  Processed 7500/8617 strategies...
  Processed 8000/8617 strategies...
  Processed 8500/8617 strategies...

Optimization complete! Found 108 strategies meeting criteria.